routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// FRONTEND
Route::group(['middleware' => 'web'], function(){

	Route::get('/', 'FrontController@index');
	Route::get('/tes', 'FrontController@tes');
	Route::get('/frontblog', 'FrontblogController@index')->name('frontblog');
	Route::get('/blog', 'FrontblogController@blog')->name('blog');
	Route::get('/blog/{id}', 'FrontblogController@show')->name('blog.show');
	Route::get('/join', 'FrontController@join')->name('join');
});

// BACKEND
Route::group(['prefix' => 'dashboard','middleware' => 'auth'], function(){
	Route::get('/anggota/export', 'AnggotaController@export')->name('anggota.export');
	Route::post('/anggota/import', 'AnggotaController@import')->name('anggota.import');
	Route::resource('blogs','BlogsController');
	Route::resource('anggota','AnggotaController');
	Route::get('/', 'DashboardController@index')->name('dashboard');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/settings/frontend', 'SetfrontController@index')->name('settings.frontend');

	//AJAX
	Route::get('/ajax_jk', 'DashboardController@ajax_jk')->name('ajax_jk');
	Route::get('/ajax_schedules', 'DashboardController@ajax_schedules')->name('ajax_schedules');
	Route::get('/ajax_delete_schedule/{id}', 'DashboardController@ajax_delete_schedule')->name('ajax_delete_schedule');
	Route::post('/ajax_add_schedule', 'DashboardController@ajax_add_schedule')->name('ajax_add_schedule');
	Route::post('/ajax_update_schedule/{id}', 'DashboardController@ajax_update_schedule')->name('ajax_update_schedule');

	//SLIDERS
	Route::get('/settings/sliders', 'SetfrontController@sliders')->name('settings.sliders');
	Route::post('/settings/create', 'SetfrontController@create_sliders')->name('settings.create');
	Route::post('/settings/sliders/delete/{id}', 'SetfrontController@delete_sliders')->name('settings.sliders.delete');
	Route::post('/sliders/edit', 'SetfrontController@edit_sliders')->name('sliders.edit');
	Route::get('/sliders/enable/{id}/{status}', 'SetfrontController@enable_sliders');

	//INFORMATIONS
	Route::get('/settings/informations', 'SetfrontController@informations')->name('settings.informations');

	Route::get('/clear-cache', function() {
		Artisan::call('cache:clear');
		return "Cache is cleared";
	});
});

app/Http/Controllers/AnggotaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Exports\UsersExport;
use App\Imports\UsersImport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Hash;
use DB;

class AnggotaController extends Controller
{
    public function index()
    {
    	$anggota = User::all();
    	return view('backend.pages.anggota.index', compact('anggota'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        // return $request->all();die;
    	$request->validate([
    		'nim' => 'required|numeric',
    		'nama' => 'required|string',
    		'password' => 'required',
    		'email' => 'required|email',
    		'telp' => 'required|numeric',
    		'tgl_lahir' => 'required|date',
    		'jk' => 'required',
    		'semester' => 'required|numeric',
    		'kelas' => 'required|string',
    		'foto' => 'required|image|max:2048',
    		'alamat' => 'required|string',
    	]);

    	$foto = $request->file('foto');
    	$new_name = date('dmYHis') .'.'. $foto->getClientOriginalExtension();
    	$foto->move(public_path('foto_anggota'), $new_name);

    	$user = new User();
    	$user->nim = $request->nim;
    	$user->name = $request->nama;
    	$user->password = bcrypt($request->password);
    	$user->email = $request->email;
    	$user->telp = $request->telp;
    	$user->tgl_lahir = $request->tgl_lahir;
    	$user->jk = $request->jk;
    	$user->semester = $request->semester;
    	$user->kelas = $request->kelas;
    	$user->foto = $new_name;
    	$user->alamat = $request->alamat;
    	$user->save();

    	return redirect()->route('anggota.index')->with('success', 'Data berhasil ditambahkan');


        // return $request->file('foto')->extension();die;

        // if ($request->file('foto')) {
        //     die('ada foto');
        // }

        // // if ($request->has(['nama','email'])) {
        // if ($request->filled(['nama','email'])) {
        //     die('yeeah nama');
        // }
        // return $request->query();die;

        // if ($request->isMethod('post')) {
        //     die('yeeah');
        // }
    }

    public function show($id)
    {
    	$user = User::findOrFail($id);
    	if (!$user) {
    		return back()->with('warning', 'Anggota tidak ditemukan');
    	}
    	return view('backend.pages.anggota.show', compact('user'));
    }

    public function edit($id)
    {
    	$user = User::findOrFail($id);
    	if (!$user) {
    		return back()->with('warning', 'Anggota tidak ditemukan');
    	}
    	return view('backend.pages.anggota.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        // return $request->all();die;
        // $user = User::findOrFail($id);

    	$request->validate([
    		'nim' => 'required|numeric',
    		'nama' => 'required|string',
    		'password' => 'required',
    		'email' => 'required|email',
    		'telp' => 'required|numeric',
    		'tgl_lahir' => 'required|date',
    		'jk' => 'required',
    		'semester' => 'required|numeric',
    		'kelas' => 'required|string',
    		'new_foto' => 'nullable|image|max:2048',
    		'alamat' => 'required|string',
    	]);

    	if ($request->new_password != '') {
    		$newPassword = bcrypt($request->new_password);
    	}else{
    		$newPassword = $request->password;
    	}

    	if ($request->hasFile('new_foto')) {
    		// $path = public_path().'\foto_anggota';
    		// if (!file_exists($path)) {
    		// 	mkdir($path, 0777, true);
    		// }
    		// unlink($path.$request->foto);
    		$new_foto = $request->file('new_foto');
    		$foto = date('dmYHis') .'.'. $new_foto->getClientOriginalExtension();
    		$new_foto->move(public_path('foto_anggota'), $foto);
    	}else{
    		$foto = $request->foto;
    	}

    	$data = array(
    		'nim' => $request->nim,
    		'name' => $request->nama,
    		'email' => $request->email,
    		'password' => $newPassword,
    		'semester' => $request->semester,
    		'kelas' => $request->kelas,
    		'foto' => $foto,
    		'alamat' => $request->alamat,
    		'tgl_lahir' => $request->tgl_lahir,
    		'jk' => $request->jk,
    		'telp' => $request->telp,
    		'telp' => $request->telp,
    	);

    	User::whereId($id)->update($data);
    	return back()->with('success', 'Data berhasil diupdate');
    }

    public function destroy($id)
    {
    	$user = User::findOrFail($id)->delete();

    	return redirect()->route('anggota.index')->with('success', 'Berhasil hapus data');
    }

    public function uploadFoto($foto){
    	$new_name = date('dmYHis') .'.'. $foto->getClientOriginalExtension();
    	$foto->move(public_path('foto_anggota'), $new_name);

    	return $new_name;
    }

    public function uploadExcel($file){
        $path =  storage_path('app');
        $new_name = 'Anggota-'.date('dmYHis') .'.'. $file->getClientOriginalExtension();
        $file->move($path, $new_name);

        return $new_name;
    }

    public function export() 
    {
        $path = public_path('files');
        if (!file_exists($path)) {
            @mkdir($path, 0777, true);
        }
        Excel::store(new UsersExport(2018), 'anggota'.date('dmYHis').'.xlsx');
        return Excel::download(new UsersExport(2018), 'users.xlsx');
    }

    public function import(Request $request) 
    {
        $file = $request->file('file');
        $new_file = $this->uploadExcel($file);
        $path =  storage_path('app');
        $data = (new UsersImport)->toArray($new_file)[0];
        unlink($path.'/'.$new_file);
        unset($data[0]);
        $anggota = [];
        $count_all_data = 0;
        $count_success_data = 0;
        $count_fail_data = 0;
        foreach ($data as $data) {
            $cek_anggota = User::where('nim',$data[0])->orWhere('email',$data[2])->first();
            if($cek_anggota){
                $count_fail_data++;
            }else{
                $tgl_lahir = empty($data[4]) ? date('Y-m-d') : date('Y-m-d', strtotime($data[4]));
                $anggota[] = [
                    'nim' => $data[0],
                    'name' => $data[1],
                    'email' => $data[2],
                    'password' => bcrypt('himsi'.date('Y')),
                    'telp' => $data[3],
                    'tgl_lahir' => $tgl_lahir,
                    'semester' => $data[5],
                    'kelas' => $data[6],
                    'jk' => $data[7],
                    'alamat' => $data[8],
                    'foto' => '',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ];
                $count_success_data++;
            }
            $count_all_data++;
        }

        DB::table('users')->insert($anggota);
        return back()->with('success', $count_success_data.' Data berhasil di import & '.$count_fail_data.' gagal diupload. Dari total '.$count_all_data.' data');
    }
}

resources/views/backend/pages/anggota/edit.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">

	<div class="page-header">
		<h1 class="title">Anggota</h1>
		<ol class="breadcrumb">
			<li><a href="{{ route('dashboard') }}">Dashboard</a></li>
			<li class="active">Anggota</li>
		</ol>

		<div class="right">
			<div class="btn-group" role="group" aria-label="...">
				<a href="index.html" class="btn btn-light">Dashboard</a>
				<a href="#" class="btn btn-light"><i class="fa fa-refresh"></i></a>
				<a href="#" class="btn btn-light"><i class="fa fa-search"></i></a>
				<a href="#" class="btn btn-light" id="topstats"><i class="fa fa-line-chart"></i></a>
			</div>
		</div>

	</div>
	<div class="container-padding">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="fieldset-form" method="POST" action="{{ route('anggota.update', $user->id) }}" enctype="multipart/form-data">
						@csrf
						@method('PATCH')
						<fieldset>
							<legend>Edit Biodata</legend>
							@if ($errors->any())
							<div class="alert alert-danger">
								<ul>
									@foreach ($errors->all() as $error)
									<li>{{ $error }}</li>
									@endforeach
								</ul>
							</div>
							@endif
							@if (Session::has('success'))
							<div class="kode-alert kode-alert-icon alert3">
								<i class="fa fa-check"></i>
								<a href="#" class="closed">&times;</a>
								{{ Session::get('success') }}
							</div>
							@endif
							<div class="form-group  col-md-6">
								<label class="form-label">NIM</label>
								<input name="nim" type="text" class="form-control" value="{{ $user->nim }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Nama</label>
								<input name="nama" type="text" class="form-control" value="{{ $user->name }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Password</label>
								<input type="password" name="new_password" class="form-control" value="">
								<input type="hidden" name="password" class="form-control" value="{{ $user->password }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Email</label>
								<input type="text" name="email" class="form-control" value="{{ $user->email }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">No. Telp / WA</label>
								<input type="telp" name="telp" class="form-control" value="{{ $user->telp }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Tanggal Lahir</label>
								<input type="date" name="tgl_lahir" class="form-control" value="{{ $user->tgl_lahir }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Jenis Kelamin</label>
								<select name="jk" class="form-control">
									<option value="L">Laki - laki</option>
									<option value="P">Perempuan</option>
								</select>
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Semester</label>
								<select name="semester" class="form-control">
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
								</select>
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Kelas</label>
								<input type="text" name="kelas" class="form-control" value="{{ $user->kelas }}">
							</div>
							<div class="form-group col-md-6">
								<img src="{{ asset('foto_anggota/'.$user->foto) }}" width="100px">
								<label class="form-label">Foto</label>
								<input type="file" name="new_foto" class="form-control">
								<input type="hidden" name="foto" class="form-control" value="{{ $user->foto }}">
							</div>
							<div class="form-group col-md-12">
								<label class="form-label">Alamat</label>
								<textarea class="form-control" name="alamat" rows="3">{{ $user->alamat }}</textarea>
							</div>
							<center><button type="submit" class="btn btn-default">Submit</button></center>
						</fieldset>
					</form>

				</div>

			</div>
		</div>
	</div>
	<!-- Start Footer -->
	@include('backend.includes.footer')
	<!-- End Footer -->


</div>
@endsection

resources/views/backend/pages/anggota/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">

	<!-- Start Page Header -->
	<div class="page-header">
		<h1 class="title">Anggota</h1>
		<ol class="breadcrumb">
			<li><a href="{{ route('dashboard') }}">Dashboard</a></li>
			<li class="active">Anggota</li>
		</ol>

		<!-- Start Page Header Right Div -->
		<div class="right">
			<div class="btn-group" role="group" aria-label="...">
				<a href="#" class="btn btn-light" data-toggle="modal" data-target="#addAnggota"><span class="fa fa-plus"></span> Tambah Anggota</a>
				<a href="{{ route('anggota.export') }}" class="btn btn-light"><i class="fa fa-file-excel-o"></i> export</a>
				<a href="#" class="btn btn-light" data-toggle="modal" data-target="#importAnggota"><span class="fa fa-plus"></span> Import Anggota</a>
			</div>
		</div>
		<!-- End Page Header Right Div -->

	</div>
	<!-- End Page Header -->

	<div class="container-padding">

		<div class="row">

			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-title">
						Data Anggota
					</div>
					@include('flash_message')
					<div class="panel-body table-responsive">

						<table id="example0" class="table display">
							<thead>
								<tr>
									<th>NIM</th>
									<th>Nama</th>
									<th>Email</th>
									<th>Semester</th>
									<th>Kelas</th>
									<th>Opsi</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($anggota as $user)
								<tr>
									<td>{{ $user->nim }}</td>
									<td>{{ $user->name }}</td>
									<td>{{ $user->email }}</td>
									<td>{{ $user->semester }}</td>
									<td>{{ $user->kelas }}</td>
									<td>
										<a href="{{ url('anggota/'.$user->id.'/edit') }}" class="btn btn-warning btn-xs"><i class="fa fa-pencil"></i></a>
										<a href="{{ url('anggota/'.$user->id) }}" class="btn btn-info btn-xs"><i class="fa fa-eye"></i></a>
										<form action="{{ route('anggota.destroy', $user->id) }}" method="POST">
											@method('DELETE')
											@csrf
											<button type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Anda yakin akan menghapus data ini ?')"><i class="fa fa-trash"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>

				</div>
			</div>
			<!-- End Panel -->
		</div>
		<!-- End Row -->
	</div>
	<!-- Start Footer -->
	<@include('backend.includes.footer')
	<!-- End Footer -->


</div>
@endsection

@section('modal')
<div class="modal fade" id="importAnggota" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Import Data Anggota Baru</h4>
			</div>
			<div class="modal-body">
				<div class="kode-alert kode-alert-icon alert5">
					<div>
						<i class="fa fa-warning"></i> PENTING
					</div>
					<p>Untuk dapat menggunakan fitur import data anggota, Kami sudah menyiapkan template Ms. Excel untuk di download. Kami sangat menyarankan untuk menggunakan template ini, Template ini kami sediakan agar tidak terjadi kesalahan input data pada proses import nanti. <a href="#" title="Download Template" class="btn btn-success btn-xs"><i class="fa fa-eye"></i> Download template disini</a></p>
					<p>Sebelum mengimport perhatikan :</p>
					<ol>
						<li>NIM dan Email mahasiswa tidak boleh sama</li>
						<li>Semua kolom yang ada di template wajib diisi agar tidak terjadi error pada saat mengimport data</li>
						<li>Untuk kolom tanggal lahir. Format penulisannya adalah, contoh : 27-02-1997</li>
						<li>Jenis kelamin harap diisi L/P saja</li>
						<li>Password defaut setiap anggota adalah "himsi2019". Password ini digunakan untuk login anggota</li>
						<li>Mohon untuk mengikuti semua peraturan ini. Kalo error saya ga tanggung jawab wkwk</li>
					</ol>
				</div>
				<form method="POST" action="{{ route('anggota.import') }}" enctype="multipart/form-data">
					@csrf
					<input type="file" name="file" required class="form-control">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-white" data-dismiss="modal">Batal</button>
					<button type="submit" class="btn btn-default">Import</button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- Modal Tambah Anggota -->
<div class="modal fade" id="addAnggota" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Data Anggota Baru</h4>
			</div>
			<form method="POST" action="{{ route('anggota.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="modal-body">
					<div class="panel panel-default">
						<div class="panel-body">
							<div class="form-group">
								<label class="form-label">NIM</label>
								<input type="number" name="nim" maxlength="8" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Nama lengkap</label>
								<input type="text" name="nama" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Password</label>
								<input type="password" name="password" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Email</label>
								<input type="email" name="email" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">No. Telp / WA</label>
								<input type="number" name="telp" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Tanggal Lahir</label>
								<input type="date" name="tgl_lahir" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Jenis Kelamin</label>
								<select name="jk" class="form-control">
									<option value="L">Laki - laki</option>
									<option value="P">Perempuan</option>
								</select>
							</div>
							<div class="form-group">
								<label class="form-label">Semester</label>
								<select name="semester" class="form-control">
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
								</select>
							</div>
							<div class="form-group">
								<label class="form-label">Kelas</label>
								<input type="text" maxlength="8" name="kelas" class="form-control form-control-line">
							</div>
							<div class="form-group">
								<label class="form-label">Foto</label>
								<input type="file" name="foto" class="form-control form-control-line" required>
							</div>
							<div class="form-group">
								<label class="form-label">Alamat</label>
								<textarea class="form-control form-control-line" name="alamat" rows="3"></textarea>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-white" data-dismiss="modal">Batal</button>
					<button type="submit" class="btn btn-default">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

@section('includeJs')
<script>
	$(document).ready(function() {
		$('#example0').DataTable();
	} );
</script>



<script>
	$(document).ready(function() {
		var table = $('#example').DataTable({
			"columnDefs": [
			{ "visible": false, "targets": 2 }
			],
			"order": [[ 2, 'asc' ]],
			"displayLength": 25,
			"drawCallback": function ( settings ) {
				var api = this.api();
				var rows = api.rows( {page:'current'} ).nodes();
				var last=null;

				api.column(2, {page:'current'} ).data().each( function ( group, i ) {
					if ( last !== group ) {
						$(rows).eq( i ).before(
							'<tr class="group"><td colspan="5">'+group+'</td></tr>'
							);

						last = group;
					}
				} );
			}
		} );

		$('#example tbody').on( 'click', 'tr.group', function () {
			var currentOrder = table.order()[0];
			if ( currentOrder[0] === 2 && currentOrder[1] === 'asc' ) {
				table.order( [ 2, 'desc' ] ).draw();
			}
			else {
				table.order( [ 2, 'asc' ] ).draw();
			}
		} );
	} );
</script>
@endsection

resources/views/backend/pages/anggota/show.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">

	<div class="page-header">
		<h1 class="title">Anggota</h1>
		<ol class="breadcrumb">
			<li><a href="{{ route('dashboard') }}">Dashboard</a></li>
			<li class="active">Anggota</li>
		</ol>

		<div class="right">
			<div class="btn-group" role="group" aria-label="...">
				<a href="index.html" class="btn btn-light">Dashboard</a>
				<a href="#" class="btn btn-light"><i class="fa fa-refresh"></i></a>
				<a href="#" class="btn btn-light"><i class="fa fa-search"></i></a>
				<a href="#" class="btn btn-light" id="topstats"><i class="fa fa-line-chart"></i></a>
			</div>
		</div>

	</div>
	<div class="container-padding">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="fieldset-form">
						<fieldset>
							<legend>Biodata</legend>
							<div class="form-group  col-md-6">
								<label class="form-label">NIM</label>
								<input type="text" class="form-control" value="{{ $user->nim }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Nama</label>
								<input type="text" class="form-control" value="{{ $user->name }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Password</label>
								<input type="password" name="password" class="form-control" value="">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Email</label>
								<input type="text" name="email" class="form-control" value="{{ $user->email }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">No. Telp / WA</label>
								<input type="telp" name="telp" class="form-control" value="{{ $user->telp }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Tanggal Lahir</label>
								<input type="date" name="tgl_lahir" class="form-control" value="{{ $user->tgl_lahir }}">
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Jenis Kelamin</label>
								<select name="jk" class="form-control">
									<option value="L">Laki - laki</option>
									<option value="P">Perempuan</option>
								</select>
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Semester</label>
								<select name="semester" class="form-control">
									<option value="1">1</option>
									<option value="2">2</option>
									<option value="3">3</option>
									<option value="4">4</option>
									<option value="5">5</option>
									<option value="6">6</option>
									<option value="7">7</option>
									<option value="8">8</option>
								</select>
							</div>
							<div class="form-group col-md-6">
								<label class="form-label">Kelas</label>
								<input type="text" name="kelas" class="form-control" value="{{ $user->kelas }}">
							</div>
							<div class="form-group col-md-6">
								<img src="{{ asset('foto_anggota/'.$user->foto) }}" width="100px">
								<label class="form-label">Foto</label>
								<input type="file" name="foto" class="form-control" value="{{ $user->foto }}">
							</div>
							<div class="form-group col-md-12">
								<label class="form-label">Alamat</label>
								<textarea class="form-control" name="alamat" rows="3">{{ $user->alamat }}</textarea>
							</div>
							<center><button type="submit" class="btn btn-default">Submit</button></center>
						</fieldset>
					</form>

				</div>

			</div>
		</div>
	</div>
	<!-- Start Footer -->
	@include('backend.includes.footer')
	<!-- End Footer -->


</div>
@endsection