routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

// FRONTEND
Route::group(['middleware' => 'web'], function(){

	Route::get('/', 'FrontController@index');
	Route::get('/tes', 'FrontController@tes');
	Route::get('/frontblog', 'FrontblogController@index')->name('frontblog');
	Route::get('/blog', 'FrontblogController@blog')->name('blog');
	Route::get('/blog/{id}', 'FrontblogController@show')->name('blog.show');
	Route::get('/join', 'FrontController@join')->name('join');
});

// BACKEND
Route::group(['prefix' => 'dashboard','middleware' => 'auth'], function(){
	Route::get('/anggota/export', 'AnggotaController@export')->name('anggota.export');
	Route::post('/anggota/import', 'AnggotaController@import')->name('anggota.import');
	Route::resource('blogs','BlogsController');
	Route::resource('anggota','AnggotaController');
	Route::get('/', 'DashboardController@index')->name('dashboard');
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/settings/frontend', 'SetfrontController@index')->name('settings.frontend');

	//AJAX
	Route::get('/ajax_jk', 'DashboardController@ajax_jk')->name('ajax_jk');
	Route::get('/ajax_schedules', 'DashboardController@ajax_schedules')->name('ajax_schedules');
	Route::get('/ajax_delete_schedule/{id}', 'DashboardController@ajax_delete_schedule')->name('ajax_delete_schedule');
	Route::post('/ajax_add_schedule', 'DashboardController@ajax_add_schedule')->name('ajax_add_schedule');
	Route::post('/ajax_update_schedule/{id}', 'DashboardController@ajax_update_schedule')->name('ajax_update_schedule');

	//SLIDERS
	Route::get('/settings/sliders', 'SetfrontController@sliders')->name('settings.sliders');
	Route::post('/settings/create', 'SetfrontController@create_sliders')->name('settings.create');
	Route::post('/settings/sliders/delete/{id}', 'SetfrontController@delete_sliders')->name('settings.sliders.delete');
	Route::post('/sliders/edit', 'SetfrontController@edit_sliders')->name('sliders.edit');
	Route::get('/sliders/enable/{id}/{status}', 'SetfrontController@enable_sliders');

	//INFORMATIONS
	Route::get('/settings/informations', 'SetfrontController@informations')->name('settings.informations');

	Route::get('/clear-cache', function() {
		Artisan::call('cache:clear');
		return "Cache is cleared";
	});
});

app/Blogs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blogs extends Model
{
    protected $fillable = ['title','posting_by','image','content'];
}

app/Http/Controllers/BlogsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blogs;

class BlogsController extends Controller
{
    public function index()
    {
        $blogs = Blogs::all();
        return view('backend.pages.blogs.index', compact('blogs'));
    }

    public function create()
    {
        return view('backend.pages.blogs.create');
    }

    public function store(Request $request)
    {
        // return $request->all();die;
        $request->validate([
            'title' => 'required|string',
            'posting_by' => 'required|string',
            'image' => 'nullable|image|max:5000|mimes:jpeg,jpg,png',
            'content' => 'required|string'
        ]);

        if ($request->hasFile('image')) {
            $new_image = $this->uploadFoto($request->file('image'));
        }else{
            $new_image = null;
        }

        $data = [
            'title' => $request->title,
            'posting_by' => $request->posting_by,
            'image' => $new_image,
            'content' => $request->content
        ];

        Blogs::create($data);
        return redirect()->route('blogs.index')->with('success', 'Artikel berhasil di posting');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $blog = Blogs::findOrFail($id);
        return view('backend.pages.blogs.edit', compact('blog'));
    }

    public function update(Request $request, $id)
    {
        // return $request->all();
        $blog = Blogs::findOrFail($id);
        $request->validate([
            'title' => 'required|string',
            'posting_by' => 'required|string',
            'image' => 'nullable|image|max:5000|mimes:jpeg,jpg,png',
            'content' => 'required|string'
        ]);

        if ($request->hasFile('image')) {
            $new_image = $this->uploadFoto($request->file('image'));
        }else{
            $new_image = $blog->image;
        }

        $blog->title = $request->title;
        $blog->content = $request->content;
        $blog->image = $new_image;
        $blog->posting_by = $request->posting_by;
        $blog->save();

        return back()->with('success', 'Blog berhasil diupdate');
    }

    public function destroy($id)
    {
        //
    }

    public function uploadFoto($file){
        $path = public_path('background_artikel');
        if (!file_exists($path)) {
            @mkdir($path, 0777, true);
        }
        $foto = date('YmdHis').'.'.$file->getClientOriginalExtension();
        $file->move($path, $foto);
        return $foto;
    }
}

resources/views/backend/pages/blogs/create.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">
	<div class="page-header">
		<h1 class="title">Blog / Artikel</h1>
		<ol class="breadcrumb">
			<li><a href="/">Dashboard</a></li>
			<li><a href="{{ route('blogs.index') }}">Blog</a></li>
			<li class="active">Create</li>
		</ol>
		<div class="right">
			<a href="{{ URL::previous() }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
		</div>
	</div>
	<!-- START CONTAINER -->
	<div class="container-padding">

		<!-- Start Row -->
		<div class="row">


			<div class="col-md-12">
				<div class="panel panel-default">

					<div class="panel-title">
						Berkreasilah Sesukamu :)
						@if(Session::has('success'))
						<div class="alert alert-success">
							{{ Session::get('success') }}
						</div>
						@endif
						@if($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach($errors->all() as $error)
								{{ $error }}
								@endforeach
							</ul>
						</div>
						@endif
					</div>

					<div class="panel-body">

						<form method="POST" action="{{ route('blogs.store') }}" enctype="multipart/form-data">
							@csrf
							<div class="form-group">
								<label class="form-label">Judul</label>
								<input name="title" type="text" class="form-control" required>
							</div>
							<div class="form-group">
								<label class="form-label">Posting By</label>
								<input type="text" name="posting_by" class="form-control" placeholder="Himsi Cimone" value="Himsi Cimone" required>
							</div>
							<div class="form-group">
								<label class="form-label">Background</label>
								<input name="image" type="file" class="form-control">
							</div>
							<label class="form-label">Konten</label>
							<textarea name="content" class="summernote"></textarea>
							<button class="btn btn-default btn-block"><i class="fa fa-paper-plane-o"></i> Posting</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Start Footer -->
	@include('backend.includes.footer')
	<!-- End Footer -->
</div>
@endsection

@section('includeJs')
<script>

	/* SUMMERNOTE*/
	$(document).ready(function() {
		$('.summernote').summernote();
	});
</script>
@endsection

resources/views/backend/pages/blogs/edit.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">
	<div class="page-header">
		<h1 class="title">Blog / Artikel</h1>
		<ol class="breadcrumb">
			<li><a href="/">Dashboard</a></li>
			<li><a href="{{ route('blogs.index') }}">Blog</a></li>
			<li class="active">Edit</li>
		</ol>
		<div class="right">
			<a href="{{ URL::previous() }}" class="btn btn-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
		</div>
	</div>
	<!-- START CONTAINER -->
	<div class="container-padding">

		<!-- Start Row -->
		<div class="row">


			<div class="col-md-12">
				<div class="panel panel-default">

					<div class="panel-title">
						Berkreasilah Sesukamu :)
						@if(Session::has('success'))
						<div class="alert alert-success">
							{{ Session::get('success') }}
						</div>
						@endif
						@if($errors->any())
						<div class="alert alert-danger">
							<ul>
								@foreach($errors->all() as $error)
								{{ $error }}
								@endforeach
							</ul>
						</div>
						@endif
					</div>

					<div class="panel-body">

						<form method="POST" action="{{ route('blogs.update', $blog->id) }}" enctype="multipart/form-data">
							@csrf
							@method('PATCH')
							<div class="form-group">
								<label class="form-label">Judul</label>
								<input name="title" type="text" class="form-control" required value="{{ $blog->title }}">
							</div>
							<div class="form-group">
								<label class="form-label">Posting By</label>
								<input type="text" name="posting_by" class="form-control" placeholder="Himsi Cimone" value="Himsi Cimone" required value="{{ $blog->posting_by }}">
							</div>
							<div class="form-group">
								<label class="form-label" style="display: block;">Background</label>
								<a href="{{ asset('background_artikel/'.$blog->image) }}" title="bg blog" target="_blank"><img src="{{ asset('background_artikel/'.$blog->image) }}" width="200px" class="img-responsive" style="margin-bottom: 5px;"></a>
								<input name="image" type="file" class="form-control">
							</div>
							<label class="form-label">Konten</label>
							<textarea name="content" class="summernote">{{ $blog->content }}</textarea>
							<button class="btn btn-default btn-block"><i class="fa fa-paper-plane-o"></i> Posting</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Start Footer -->
	@include('backend.includes.footer')
	<!-- End Footer -->
</div>
@endsection

@section('includeJs')
<script>

	/* SUMMERNOTE*/
	$(document).ready(function() {
		$('.summernote').summernote();
	});
</script>
@endsection

resources/views/backend/pages/blogs/index.blade.php
@extends('backend.layouts.master')

@section('content')
<div class="content">

	<!-- Start Page Header -->
	<div class="page-header">
		<h1 class="title">Blogs / Artikel</h1>
		<ol class="breadcrumb">
			<li><a href="/">Dashboard</a></li>
			<li class="active">Blogs</li>
		</ol>

		<!-- Start Page Header Right Div -->
		<div class="right">
			<!-- <div class="btn-group" role="group" aria-label="..."> -->
				<a href="{{ route('blogs.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Buat Blog</a>
				<!-- </div> -->
			</div>
			<!-- End Page Header Right Div -->

		</div>
		<!-- End Page Header -->

		<!-- START CONTAINER -->
		<div class="container-padding">

			<!-- Start Row -->
			<div class="row">


				<div class="col-md-12">
					<div class="panel panel-default">

						<div class="panel-title">
							Our Blogs
							@include('flash_message')
						</div>

						<div class="panel-body">

							<!-- Start BlogPost -->
							@if(count($blogs) == 0)
							<div class="kode-alert kode-alert-icon alert5">
								<center><i class="fa fa-warning"></i>Belum ada blog yang dibuat. Silahkan buat dahulu :)</center>
							</div>
							@else
							@foreach($blogs as $blog)
							<div class="col-md-4">
								<div class="panel panel-widget blog-post">
									<div class="panel-body">

										<div class="image-div color10-bg">
											<img src="{{ asset('background_artikel/'.$blog->image) }}" class="image" alt="img">
											<h1 class="title"><a href="#">{{ $blog->title }}</a></h1>
										</div>
										<p class="text">{{ substr($blog->content, 0, 100) }}...</p>
										<div>
											<a href="#" sty>Read More</a> <a href="{{ url('blogs/'.$blog->id.'/edit') }}" class="btn btn-primary btn-xs pull-right"><i class="fa fa-pencil"></i> Edit</a>
										</div>
										<hr style="margin: 0;">
										<div><strong>By : </strong>{{ $blog->posting_by }}</div>
										<div><strong>Created At : </strong>{{ $blog->created_at }}</div>
										<div><strong>View : </strong>{{ $blog->view }} <i class="fa fa-eye"></i></div>
										<div><strong>Like : </strong>{{ $blog->like }} <i class="fa fa-thumbs-up"></i></div>
										<div><strong>Tags : </strong>{{ $blog->tags }}</div>
									</div>
								</div>
							</div>
							@endforeach
							@endif
							<!-- End BlogPost -->      
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Start Footer -->
		@include('backend.includes.footer')
		<!-- End Footer -->
	</div>
	@endsection

	@section('includeJs')
	<script>

		/* SUMMERNOTE*/
		$(document).ready(function() {
			$('.summernote').summernote();
		});
	</script>
	@endsection

resources/views/backend/pages/blogs/show.blade.php
@extends('backend.layouts.master')

@section('content')

@endsection